# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 5.5
    - php: 5.6

before_script:
  - composer install

script: php generator.php

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "mcleague@126.com"