language: php

php:
  - 7.1
  - 7.2

before_script:
  - rm -rf output
  - composer install

script: php generator.php

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "mcleague@126.com"